'use strict';
document.body.classList.add('js');
const menu=document.querySelector('#menu'),navigation=document.querySelector('#navigation');
if(menu&&navigation){const close=()=>{navigation.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Explorar menú';};menu.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Cerrar menú':'Explorar menú';});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',close));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&navigation.classList.contains('open')){close();menu.focus();}});}
const paths={personal:['RUTA PERSONAL','Primero, entiende qué estás mirando.','Distingue el impuesto, el período y la autoridad. Tus ingresos, compras y bienes pueden llevarte a temas diferentes.'],independiente:['RUTA INDEPENDIENTE','Conecta tu actividad con los conceptos.','Explora ingresos, soportes y retenciones. Después verifica tus responsabilidades y las reglas que correspondan a tu actividad y período.'],negocio:['RUTA DE NEGOCIO','No confundas la operación con la obligación.','Acércate al IVA, al ICA y a las responsabilidades del RUT. Tener un negocio no significa que todos los tratamientos sean iguales.']};
function setSelected(button,selector){document.querySelectorAll(selector).forEach(item=>{const active=item===button;item.classList.toggle('selected',active);item.setAttribute('aria-pressed',String(active));});}
document.querySelectorAll('[data-path]').forEach(button=>button.addEventListener('click',()=>{setSelected(button,'[data-path]');const content=paths[button.dataset.path];['path-label','path-title','path-description'].forEach((id,index)=>document.getElementById(id).textContent=content[index]);}));
const scenarios={
 pago:['INGRESOS Y RETENCIONES','Lo recibido y lo retenido no son lo mismo.','En algunos pagos puede practicarse una retención según las reglas aplicables. La retención es un mecanismo de recaudo anticipado, no un impuesto adicional por sí mismo.','¿Qué concepto me retuvieron y qué soporte debo conservar?','https://normograma.dian.gov.co/dian/compilacion/docs/oficio_dian_906765_2022.htm','DIAN'],
 compra:['OPERACIONES Y TRATAMIENTOS','El total no explica todo por sí solo.','Una compra puede llevarte a revisar el IVA y su tratamiento. No todas las operaciones tienen la misma tarifa o condición; verifica el concepto y sus reglas.','¿Qué impuesto y tratamiento corresponden a esta operación?','https://normograma.dian.gov.co/dian/compilacion/docs/oficio_dian_0441_2018.htm','DIAN'],
 actividad:['ACTIVIDAD Y TERRITORIO','El lugar también importa.','El ICA se relaciona con actividades industriales, comerciales y de servicios. Consulta la jurisdicción y las reglas locales; la información de una ciudad no sirve para todas.','¿Cuál es la autoridad competente para mi actividad?','https://www.haciendabogota.gov.co/es/impuestos/impuesto-de-industria-y-comercio-ica','Hacienda de Bogotá · ejemplo local'],
 inmueble:['BIENES Y AUTORIDAD LOCAL','Empieza por ubicar el inmueble.','Para conocer el predial, identifica la entidad territorial correspondiente. El calendario y las condiciones se verifican en su portal oficial.','¿Dónde consulto las reglas y el período de este predio?','https://www.haciendabogota.gov.co/es/sdh/impuestos-bogota','Hacienda de Bogotá · ejemplo local']
};
document.querySelectorAll('[data-scenario]').forEach(button=>button.addEventListener('click',()=>{setSelected(button,'[data-scenario]');const content=scenarios[button.dataset.scenario];['scenario-label','scenario-title','scenario-description','scenario-question'].forEach((id,index)=>document.getElementById(id).textContent=content[index]);const link=document.querySelector('#scenario-source');link.href=content[4];link.textContent='Consultar fuente oficial · '+content[5];}));
// Ejercicio aritmético: el porcentaje no es una tarifa tributaria aplicable.
function splitPayment(gross,rate){if(!Number.isFinite(gross)||!Number.isFinite(rate)||gross<0||gross>1e12||rate<0||rate>30)throw new Error('Usa un importe entre 0 y 1.000.000.000.000 y un porcentaje entre 0 y 30.');const separated=gross*rate/100;return{gross,separated,remaining:gross-separated};}
const form=document.querySelector('#lab-form');
if(form){const gross=document.querySelector('#gross'),rate=document.querySelector('#rate'),error=document.querySelector('#lab-error'),result=document.querySelector('#lab-result');const money=new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',minimumFractionDigits:2,maximumFractionDigits:2});
 function render(){try{if(gross.value.trim()==='')throw new Error('Completa el valor del pago.');const values=splitPayment(Number(gross.value),Number(rate.value));document.querySelector('#gross-result').textContent=money.format(values.gross);document.querySelector('#tax-result').textContent=money.format(values.separated);document.querySelector('#net-result').textContent=money.format(values.remaining);document.querySelector('#net-bar').style.width=(100-Number(rate.value))+'%';document.querySelector('#tax-bar').style.width=rate.value+'%';document.querySelector('#lab-equation').textContent=money.format(values.gross)+' × '+rate.value+'% = '+money.format(values.separated);result.hidden=false;error.hidden=true;}catch(problem){result.hidden=true;error.textContent=problem.message;error.hidden=false;}}
 rate.addEventListener('input',()=>{document.querySelector('#rate-label').textContent=rate.value+'%';render();});gross.addEventListener('input',()=>{result.hidden=true;error.hidden=true;});form.addEventListener('submit',event=>{event.preventDefault();render();});
}
const thoughts={rut:[false,'El RUT es un registro, no un impuesto. Identifica, ubica y clasifica sujetos de obligaciones ante la DIAN.'],local:[false,'Debes verificar el calendario de la autoridad competente y del período correcto. Las fechas de otra ciudad no se trasladan a tu caso.'],retencion:[true,'La retención es un mecanismo de recaudo anticipado. Su aplicación y tratamiento deben verificarse según las reglas del concepto.']};
document.querySelectorAll('[data-thought]').forEach(article=>{article.querySelectorAll('[data-answer]').forEach(button=>button.addEventListener('click',()=>{article.querySelectorAll('[data-answer]').forEach(item=>{const active=item===button;item.classList.toggle('selected',active);item.setAttribute('aria-pressed',String(active));});const thought=thoughts[article.dataset.thought],correct=(button.dataset.answer==='true')===thought[0];const feedback=article.querySelector('.thought-feedback');feedback.textContent=(correct?'¡Correcto! ':'Veámoslo de nuevo: ')+thought[1];feedback.hidden=false;}));});
const reset=document.querySelector('#reset-thoughts');if(reset)reset.addEventListener('click',()=>{document.querySelectorAll('[data-thought]').forEach(article=>{article.querySelectorAll('[data-answer]').forEach(button=>{button.classList.remove('selected');button.setAttribute('aria-pressed','false');});const feedback=article.querySelector('.thought-feedback');feedback.hidden=true;feedback.textContent='';});});